# These variables define the project; they may not need to be changed
project:
  type: book
  output-dir: _book

# These variables define the book contents - adjust them as necessary
book:
  # [A] BOOK TITLE
  title: "BM110 Microbiology Calculations Workshop"
  reader-mode: true
  
  # The cover image and favicon; these may not need to be changed
  cover-image: sipbs_compbio_800.png
  favicon: icon_32.png
  
  # Sets the page footer text/images
  # [B] FOOTER TEXT
  page-footer:
    left: |
      BM110 Microbiology Calculations Workshop
    right: |
      Dr Morgan Feeney & Dr Suzie Humphrey

  # Sets the URL for the repository
  # [C] GITHUB REPOSITORY URL
  repo-url: https://github.com/mafeeney/BM110micro
  repo-branch: main
  repo-actions: [edit, issue]

  # Sets author information and publication/presentation date
  # [D] AUTHOR INFORMATION AND PUBLICATION/PRESENTATION DATE
  author: "Dr Morgan Feeney"
  date: "02/02/26"

  # Define chapters and sections here
  # [E] CHAPTERS AND SECTIONS
  chapters:
    - index.qmd
    - intro.qmd
    - part: task01.qmd
      chapters: 
        - task01a.qmd
        - task01b.qmd
        - task01c.qmd
    - part: task02.qmd
      chapters: 
        - task02a.qmd
        - task02b.qmd
    - part: task3.qmd
      chapters: 
        - task03a.qmd
        - task03b.qmd
    - part: task04.qmd
      chapters: 
        - task04a.qmd
        - task04b.qmd
    
# Location of BibTeX format reference file; may not need to be changed


# Formatting and theme; may not need to be changed
# The custom-styles.css is added to provide custom callouts
# These may be changed as desired for your project, or removed if unwanted
format:
  html:
    theme: cosmo
    code-link: true
    author-meta: "Morgan Feeney"
    #css: custom-styles.css
  epub:
    cover-image: cover.png
  docx:
    cover-image: cover.png
    toc-depth: 1
    link-citations: true
    link-bibliography: true

# Freeze output before pushing modifications to the repository when publishing
# Should not need changing
execute:
  freeze: auto

# Add custom callouts
custom-callout:
  callout-case-study:
    title: "Case Study"
    icon-symbol: "üîç"
    color: "#FFA500"
  callout-data:
    icon-symbol: "üìä"
    title: "Data Analysis"
    color: "#32CD32"
  callout-discussion:
    title: "Discussion Questions:"
    icon-symbol: "‚ú®"
    color: "#BA55D3"
  callout-microbe:
    title: "Microbe Profile"
    icon-symbol: "üß´"
    color: "#1E90FF"
  callout-thumbs-up:
    title: "Great job!"
    icon-symbol: "üëç"
    color: "#008000"
  callout-todo:
    icon-symbol: "üìù"
    color: "pink"
  callout-challenge:
    title: "Challenge"
    icon-symbol: "üßë‚Äçüè´"
    color: "aquamarine"
  callout-question:
    title: "Question"
    icon-symbol: "üôã"
    color: "yellow"
  callout-questions:
    title: "Questions"
    icon-symbol: "üôãÔ∏è"
    color: "yellow"    

filters:
  - custom-callout
  - naquiz
